# Site settings
title: Phuong Nguyen #Towardthesea
email: phuong.nguyen@iit.it
url: https://towardthesea.github.io
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "Something about me, a roboticist, programmer, photographer, cook"
skills: "Robotics Researcher - PhD Fellow - Amature Photographer & Cook"
meta_author: Phuong D.H. NGUYEN

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: phuong

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2dc4c1 #18bc9c #80B3FF
  primary-rgb: "45,196,193" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Phuong D.H. Nguyen #Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/towardthesea_vn
#  - title: facebook
#    url:
  - title: linkedin
    url: https://www.linkedin.com/in/phuong-d-h-nguyen/
  - title: github
    url: http://github.com/towardthesea

# Postal address (add as many lines as necessary)
address:
  - line: <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> phuong (dot) nguyen [at] iit (dot) it	
  - line: iCub Facility
  - line: <a href="https://iit.it/">Istituto Italiano di Tecnologia</a>
  - line: Via Morego, 30
  - line: Genova 16163, Italy
  


# Credits content
credits: 'This page is created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
